USE SQL4
GO
DROP PROCEDURE createClientType
DROP PROCEDURE createCarType
DROP PROCEDURE createCarState
DROP PROCEDURE createClient
DROP PROCEDURE createCar
DROP PROCEDURE createCarHire
DROP PROCEDURE readAll
DROP PROCEDURE readAllCar
DROP PROCEDURE readAllClient
DROP PROCEDURE readAllById
DROP PROCEDURE readCarById
DROP PROCEDURE readClientById
DROP PROCEDURE updateCar
DROP PROCEDURE updateClient
DROP PROCEDURE updateCarHire
DROP PROCEDURE deleteClientType
DROP PROCEDURE deleteCarType
DROP PROCEDURE deleteCarState
DROP PROCEDURE deleteCar
DROP PROCEDURE deleteClient
DROP PROCEDURE deleteCarHire
GO
USE master
GO